apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: template-seed-image
  namespace: fleet-default
spec:
  baseImage: registry.suse.com/rancher/elemental-teal-iso/5.4:1.2.3
  cloud-config:
  cleanupAfterMinutes: 60
  registrationRef:
    name: d-endpoint
    namespace: fleet-default
  retriggerBuild: false
