apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: https://rancher.lab.k8/elemental/registration/tsshvqjbqqmrt4rcvzhnqxj9l5bglvxns725dhhdtlwhw6drf229rz
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: linux
    elemental:
      install:
        debug: true
        device: /dev/sda
        poweroff: true
        reboot: true
      registration:
        auth: tpm
        emulate-tpm: true
      reset:
        reboot: true
        reset-oem: true
        reset-persistent: true
